CREATE TABLE IF NOT EXISTS instructors (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS packs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    year INTEGER NOT NULL,
    semester INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS courses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL CHECK (type IN ('COMPULSORY', 'OPTIONAL')),
    code VARCHAR(50) NOT NULL UNIQUE,
    abbr VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    instructor_id BIGINT REFERENCES instructors(id),
    pack_id BIGINT REFERENCES packs(id),
    group_count INTEGER NOT NULL DEFAULT 1,
    description TEXT
);
